// react-todo/src/components/TodoList.jsx
import React from 'react';
import { TodoItem } from './TodoItem';
import './TodoList.css';

export class TodoList extends React.Component {

    constructor(props) {

        super(props);
        this.state = {
            listArray: [ {text: "Order shopping", isDone: false}, {text: "Clean house", isDone: false}],
            newItem: ""
        };

        this.handleAddItem = this.handleAddItem.bind(this);
        this.handleTextChange = this.handleTextChange.bind(this);
      }

      handleTextChange(event) {
        this.setState({ 
            newItem: event.target.value 
        })
      }

      handleAddItem(event) {
        event.preventDefault();
        let newItem = {text: this.state.newItem, isDone: false};
        this.setState({ 
            listArray: [...this.state.listArray, newItem],
            newItem: ""
        })
      }

    render() {
        var items = [];
        items = this.state.listArray.map((item, index) => {
            return <TodoItem key={index} text={item.text} isDone={item.isDone}/>
        })
      
        return (
            <div>
                {items}
                <form>
                    <input
                        value={this.state.newItem}
                        onChange={this.handleTextChange}
                        type="text" />
                    <button onClick={this.handleAddItem}>
                        Add Item
                    </button>
                </form>
            </div>
        )
      }
  }

// vue-todo/src/components/TodoList/TodoList.vue
<template>
  <div id="todo-list">
    <ul>
      <li v-for="item in todoList" :key="item.text">
        <TodoItem v-bind:text="item.text" v-bind:isDone="item.isDone" />
      </li>
    </ul>
    <input type="text" v-model="newItem"/>
    <button v-on:click="addItem">Add Item</button>
  </div>
</template>

<script src="./TodoList.js"></script>
